apiVersion: v1
kind: Pod
metadata:
  name: payment-service-pod
  namespace: microservices
  labels:
    app: payment-service
spec:
  containers:
    - name: payment-service
      image: order-management-system-payment-service:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8081
      env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"
        - name: SERVER_PORT
          value: "8081"
