pipeline {
    agent any
    tools {
        maven 'Maven-3.9.11'
    }
    stages {
        stage('Compile') {
            steps {
                sh 'cd inventory-service && mvn clean compile'
            }
        }
        stage('Test') {
            steps {
                sh 'cd inventory-service && mvn test'
            }
        }
        stage('Build') {
            steps {
                sh 'cd inventory-service && mvn package'
            }
        }
    }
}